# Generated by Django 6.0.2 on 2026-04-06 19:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_orchestration", "0009_workflowdeployment_font_color_and_more"),
        ("users", "0018_create_chatbot_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowdeployment",
            name="font_color",
            field=models.CharField(
                default="#000000",
                help_text="Font color for chatbot text (hex format)",
                max_length=7,
            ),
        ),
        migrations.CreateModel(
            name="ChatbotSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("workflow_id", models.IntegerField(blank=True, null=True)),
                ("label", models.CharField(default="New Conversation", max_length=200)),
                ("conversation_history", models.JSONField(default=list)),
                ("message_count", models.IntegerField(default=0)),
                ("preview", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chatbot_sessions",
                        to="users.intellidocproject",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
