# Generated by Django 6.0.2 on 2026-04-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_orchestration", "0010_create_chatbot_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatbotsession",
            name="workflow_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
