# Generated by Django 6.0.2 on 2026-04-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_add_analytics_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intellidocproject",
            name="preserve_original_folder_structure",
            field=models.BooleanField(
                default=True,
                help_text="LLM-based folder organization using per-document short summaries",
            ),
        ),
    ]
